#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	NEWBTNSCRIPT,
	ENDBTNSCRIPT,
	LOBBYHDSCRIPT,
	RECRUITMENTBTNSCRIPT,
	TRAINNINGBTNSCRIPT,
	SQUADBTNSCRIPT,
	CURSORSCRIPT,
	PROCEEDBTNSCRIPT,
	LOBBYBTNSCRIPT,
	MGRBTNSCRIPT,
	RECRUITMENTSCRIPT,
	RECRUITSLOTSCRIPT,
	GAMERSCRIPT,
	CHAMPSCRIPT,
	ARCHERSCRIPT,
	ARROWSCRIPT,
	FIGHTERSCRIPT,
	EFFECTSCRIPT,
	KNIGHTSCRIPT,
	MONKSCRIPT,
	NINJASCRIPT,
	NINJACLONESCRIPT,
	PRIESTSCRIPT,
	TEAMHEADERSCRIPT,
	BLUETEAMSLOTSCRIPT,
	LINEUPBGSCRIPT,
	LINEUPTEAMSCRIPT,
	DRAFTARROWSCRIPT,
	LINEUPSLOTSCRIPT,
	NEXTBTNSCRIPT,
	TEAMSLOTSCRIPT,
	BANPICKUISCRIPT,
	TEAMSLOTICONSCRIPT,
	BANSSLOTSCRIPT,
	CHAMPSLOTSCRIPT,
	MIDDLEBANSCRIPT,
	BATTLESTARTBTNSCRIPT,
	BATTLESTADIUMSCRIPT,
	REDTEAMSLOTSCRIPT,
	BATTLERESULTSCRIPT,
	BATTLEENDBTNSCRIPT,
	CURTAINSCRIPT,
	MCSCRIPT,
	TEXTBOXSCRIPT,
	TEXTEFFECTSCRIPT,
	AVATARSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
